export const presidents = [
  {
    fname: "Avirup",
    lname: "Chattaraj",
    role: "PRESIDENT",
    image: "avirup",
    github: "severussnape123",
    linkedin: "avirupchattaraj",
  },
  {
    fname: "Hritik",
    lname: "Bhandari",
    role: "PRESIDENT",
    image: "hritik",
    github: "hritikbhandari",
    linkedin: "hritikbhandari",
  },
];

export const board = [
  {
    fname: "Anush",
    lname: "Bhatia",
    role: "TECHNICAL DIRECTOR",
    image: "anush",
    github: "anushbhatia",
    linkedin: "anush-bhatia-aa500a158",
  },
  {
    fname: "Hariom",
    lname: "Palkar",
    role: "CORPORATE DIRECTOR",
    image: "hariom",
    github: "aannuuj",
    linkedin: "hariompalkar",
  },
  {
    fname: "Takshil",
    lname: " Mittal",
    role: "EVENTS DIRECTOR",
    image: "takshil",
    github: "takshilmittal",
    linkedin: "takshil-mittal",
  },
  {
    fname: "Pratyaksh",
    lname: "Bhalla",
    role: "EXECUTIVE DIRECTOR",
    image: "pratyaksh",
    github: "pratyaksh64",
    linkedin: "pratyaksh-bhalla-96871b186",
  },
];

export const leads = [
  {
    fname: "Akshat",
    lname: "Anand",
    role: "PROJECTS LEAD",
    image: "akshat",
    github: "cipheraxat",
    linkedin: "akshatanand1999",
  },
  {
    fname: "Gayathri",
    lname: "Seetharaman",
    role: "R&D LEAD",
    image: "gayathri",
    github: "Gayathri621",
    linkedin: "gayathri-seetharaman-964986158",
  },
  {
    fname: "Yashvardhan",
    lname: "Jagnani",
    role: "WEB DEVELOPMENT LEAD",
    image: "yashvardhan",
    github: "jagnani73",
    linkedin: "yashvardhan-jagnani",
  },
];

export const members = [
  {
    fname: "Abhinav",
    lname: "Verma",
    role: "WEB DEVELOPMENT",
    image: "abhinav",
    github: "abhinav565",
    linkedin: "abhinav-verma-3752701a2",
  },
  {
    fname: "Abhishek",
    lname: "Saxena",
    role: "ML",
    image: "abhishek",
    github: "saxenabhishek",
    linkedin: "abhibored",
  },

  {
    fname: "Bhavya",
    lname: "Chhabra",
    role: "ML",
    image: "bhavya",
    github: "bhavya1600",
    linkedin: "bhavya-chhabra-1600",
  },
  {
    fname: "Devansh",
    lname: "Goswami",
    role: "MANAGER",
    image: "devansh",
    github: "",
    linkedin: "devansh-goswami-74590a187",
  },

  {
    fname: "Himanshu",
    lname: "Tiwari",
    role: "CORPORATE",
    image: "himanshu",
    github: "",
    linkedin: "",
  },
  {
    fname: "Karan",
    lname: "Sharma",
    role: "CONTENT",
    image: "karan",
    github: "",
    linkedin: "",
  },
  {
    fname: "Kartik",
    lname: "Mohan",
    role: "ML",
    image: "kartik",
    github: "kartikmohan123",
    linkedin: "kartik-mohan",
  },
  {
    fname: "Palak",
    lname: "Trivedi",
    role: "PHOTOGRAPHER",
    image: "palak",
    github: "palaktrivedii",
    linkedin: "palak-trivedi-5bb2261a8",
  },
  {
    fname: "Sampada",
    lname: "Bareja",
    role: "ANALYTICS",
    image: "sampada",
    github: "",
    linkedin: "sampada-bareja-43930818b",
  },
  {
    fname: "Shubhangi",
    lname: "Soni",
    role: "ML",
    image: "shubhangi",
    github: "ShubhangiSoni1603",
    linkedin: "shubhangi-soni",
  },
  {
    fname: "Sourjayon",
    lname: "Nath",
    role: "GRAPHIC DESIGNER",
    image: "sourjayon",
    github: "insistence-essenn",
    linkedin: "sourjayon-nath-557a43174",
  },
  {
    fname: "Tejas",
    lname: "Chintala",
    role: "ML",
    image: "tejas",
    github: "arcado10",
    linkedin: "tejas-chintala-752918188",
  },
  {
    fname: "Utkarsh",
    lname: "Chaurasia",
    role: "ML",
    image: "utkarsh",
    github: "UtkarshChaurasia",
    linkedin: "utkarsh-chaurasia-a4b76a17b",
  },
];
