export const presidents = [
    {
        fname: "Abhay",
        lname: "Lal",
        role: "PRESIDENT",
        image: "abhay.jpeg",
        github: "abhay-lal",
        linkedin: "abhay-l-6850111bb/",
    },
    {
        fname: "Aadit",
        lname: "Bhargawa",
        role: "Vice President",
        image: "aadit.png",
        github: "",
        linkedin: "aadit-bhargava-b58507200/"
    }
];

export const board = [
    {
        fname: "Aditya",
        lname: "Jain",
        role: "TECHNICAL DIRECTOR",
        image: "aditya.jpeg",
        github: "adityajain2048",
        linkedin: "aditya-jain-b5040a1b8/",
    },
    {
        fname: "Arun",
        lname: "Jangra",
        role: "TECHNICAL DIRECTOR",
        image: "arun.jpeg",
        github: "Arun89-crypto",
        linkedin: "arun-jangra-4a94b41b5/",
    },
    {
        fname: "Tanmay",
        lname: "Agrawal",
        role: "PROJECT DIRECTOR",
        image: "tanmay.jpg",
        github: "Vector3103",
        linkedin: "tanmay-agrawal-b685531b0",
    },
    {
        fname: "Tanisha",
        lname: "Kapoor",
        role: "CREATIVES DIRECTOR",
        image: "tanisha.jpg",
        github: "tanishakapoor11",
        linkedin: "tanisha-kapoor-4713261a0/",
    },
    {
        fname: "Surya",
        lname: "Reddy",
        role: "CORPORATE DIRECTOR",
        image: "surya.jpeg",
        github: "",
        linkedin: "gnana-surya-teja-reddy/",
    },
    {
        fname: "Nandini",
        lname: "Agrawal",
        role: "ASSO. CORPORATE DIRECTOR",
        image: "nandini.jpeg",
        github: "",
        linkedin: "nandini-agrawal-851815225/",
    },
    {
        fname: "Arpita",
        lname: "Singh",
        role: "CORPORATE DIRECTOR",
        image: "arpita.jpeg",
        github: "arpitasingh13",
        linkedin: "arpitasingh1301/",
    },
];

export const advisor = [

    {
        fname: "Anush",
        lname: "Bhatia",
        role: "TECHNICAL ADVISOR",
        image: "anush.jpg",
        github: "anushbhatia",
        linkedin: "anush-bhatia-aa500a158",
    },
    {
        fname: "Avirup",
        lname: "Chattaraj",
        role: "TECHNICAL ADVISOR",
        image: "avirup.jpg",
        github: "severussnape123",
        linkedin: "avirupchattaraj",
    },
    {
        fname: "Hritik",
        lname: "Bhandari",
        role: "TECHNICAL ADVISOR",
        image: "hritik.jpg",
        github: "hritikbhandari",
        linkedin: "hritikbhandari",
    },

    {
        fname: "Pratyaksh",
        lname: "Bhalla",
        role: "TECHNICAL ADVISOR",
        image: "pratyaksh.jpg",
        github: "pratyaksh64",
        linkedin: "pratyaksh-bhalla-96871b186",
    },
    {
        fname: "Takshil",
        lname: " Mittal",
        role: "EVENTS ADVISOR",
        image: "takshil.jpg",
        github: "takshilmittal",
        linkedin: "takshil-mittal",
    },
    {
        fname: "Akshat",
        lname: "Anand",
        role: "PROJECTS ADVISOR",
        image: "akshat.jpg",
        github: "cipheraxat",
        linkedin: "akshatanand1999",
    },
    {
        fname: "Gayathri",
        lname: "Seetharaman",
        role: "RESEARCH & DEVELOPMENT ADVISOR",
        image: "gayathri.jpg",
        github: "Gayathri621",
        linkedin: "gayathri-seetharaman-964986158",
    },
    {
        fname: "Shubhangi",
        lname: "Soni",
        role: "CORPORATE ADVISOR",
        image: "shubhangi.jpeg",
        github: "ShubhangiSoni1603",
        linkedin: "shubhangi-soni",
    },
    {
        fname: "Soumya",
        lname: "Kundu",
        role: "EDITORIAL ADVISOR",
        image: "soumya.jpeg",
        github: "aymuos15",
        linkedin: "soumya-snigdha-kundu-84b812183",
    },
    {
        fname: "Stuti",
        lname: "Sehgal",
        role: "TECHNICAL ADVISOR",
        image: "stuti.jpg",
        github: "stutisehgal",
        linkedin: "stuti-sehgal-7a10301b1",
    },
    {
        fname: "Ishika",
        lname: "Gupta",
        role: "PUBLIC RELATIONS ADVISOR",
        image: "ishika.jpg",
        mail: "ishikag2050@gmail.com",
        linkedin: "findishika",
    },
    {
        fname: "Sheel",
        lname: "Patel",
        role: "TECHNICAL ADVISOR",
        image: "sheel.jpg",
        github: "sheel1206",
        linkedin: "sheel1206",
    },
    {
        fname: "Shaswat",
        lname: "Srivastava",
        role: "TECHNICAL ADVISOR",
        image: "shaswat.jpeg",
        github: "shaas1704",
        linkedin: "shaswat-srivastava-03a67118b/",
    },
    {
        fname: "Rakesh",
        lname: "J",
        role: "PROJECTS ADVISOR",
        image: "rakesh j.jpg",
        github: "stagnito",
        linkedin: "rakesh-j-35174618b",
    },
    {
        fname: "Aarsh",
        lname: "Chaube",
        role: "RESEARCH & DEVELOPMENT ADVISOR",
        image: "aarsh.jpg",
        github: "Aarsh2001",
        linkedin: "aarsh-chaube-0099521a1",
    },
    {
        fname: "Udit",
        lname: "Dhawan",
        role: "CORPORATE ADVISOR",
        image: "udit.jpg",
        github: "udit2812",
        linkedin: "udit-dhawan-819762166/",
    },
    {
        fname: "Abhimanyu",
        lname: "Bhadauria",
        role: "CREATIVES ADVISOR",
        image: "abhimanyu.png",
        github: "Mnayu",
        linkedin: "abhimanyu2911",
    },
    {
        fname: "Shubhank",
        lname: "Sargam",
        role: "CREATIVES ADVISOR",
        image: "shubhank.jpg",
        github: "shubhanksargam",
        linkedin: "shubhanks/",
    },
    {
        fname: "Ankit",
        lname: "Hans",
        role: "TECHNICAL ADVISOR",
        image: "ankit.jpeg",
        github: "ankithans",
        linkedin: "ankithans",
    },
    {
        fname: "Palak",
        lname: "Aggarwal",
        role: "TECHNICAL ADVISOR",
        image: "palak.jpeg",
        github: "Palak-Aggarwal1234",
        linkedin: "palak-aggarwal-96366a18b/",
    },
];

export const techmembers = [
    // {
    //     fname: "Aman Singh",
    //     lname: "Kanwar",
    //     role: "ML Engineer",
    //     image: "aman.jpg",
    //     github: "amandotexe",
    //     linkedin: "aman-kanwar-5955651b8",
    // },
    // {
    //     fname: "Anushree",
    //     lname: "Bajaj",
    //     role: "ML Engineer",
    //     image: "anushree.jpg",
    //     github: "condescendo",
    //     linkedin: "anushree-bajaj-7486b71b9/",
    // },
    {
        fname: "Aryan",
        lname: "Karoliwal",
        role: "ML Engineer",
        image: "aryan.jpg",
        github: "xxNitroprasad",
        linkedin: "aryankaroliwal",
    },
    {
        fname: "Jahnavi",
        lname: "Darbhamulla",
        role: "Web Developer",
        image: "jahnavi.jpg",
        github: "JahnaviDarbhamulla",
        linkedin: "jahnavi-darbhamulla-0a4280201/",
    },
    {
        fname: "Kruthi",
        lname: "M",
        role: "ML Engineer",
        image: "kruthi.jpeg",
        github: "Kruthim1304",
        linkedin: "kruthi-m-49b300200/",
    },
    {
        fname: "Thrishalini",
        lname: "Dwaraknath",
        role: "ML Engineer",
        image: "thrishalini.jpg",
        github: "thrishalini1",
        linkedin: "thrishalini-d-3234b21b7/",
    },
    {
        fname: "Utkarsh",
        lname: "Upendra",
        role: "ML Engineer",
        image: "utkarsh.JPG",
        github: "Utkarsh3012",
        linkedin: "utkarsh-upendra-b382891ba/",
    },
];

export const designmembers = [
    // {
    //     fname: "Syed",
    //     lname: "Amaan Ariz",
    //     role: "Designer",
    //     image: "syed.jpg",
    //     github: "SYEDAMAAN05",
    //     linkedin: "syed-amaan-430a7b1b2",
    // },
];

export const mgmtmembers = [
    // {
    //     fname: "Abhishek",
    //     lname: "Dubey",
    //     role: "Content Writer",
    //     image: "abhishekDubey.jpg",
    //     github: "",
    //     linkedin: "abhishek-dubey-4b76161b8",
    // },
];
