export const presidents = [
  {
    fname: "Hritik",
    lname: "Bhandari",
    role: "FOUNDER & PRESIDENT ",
    image: "hritik.jpg",
    github: "hritikbhandari",
    linkedin: "hritikbhandari",
  },
  {
    fname: "Pratyaksh",
    lname: "Bhalla",
    role: "VICE PRESIDENT",
    image: "pratyaksh.jpg",
    github: "pratyaksh64",
    linkedin: "pratyaksh-bhalla-96871b186",
  },
];

export const board = [
  {
    fname: "Takshil",
    lname: " Mittal",
    role: " EVENTS DIRECTOR ",
    image: "takshil.jpg",
    github: "takshilmittal",
    linkedin: "takshil-mittal",
  },
  {
    fname: "Akshat",
    lname: "Anand",
    role: "PROJECTS DIRECTOR",
    image: "akshat.jpg",
    github: "cipheraxat",
    linkedin: "akshatanand1999",
  },
  {
    fname: "Gayathri",
    lname: "Seetharaman",
    role: "RESEARCH & DEVELOPMENT DIRECTOR",
    image: "gayathri.jpg",
    github: "Gayathri621",
    linkedin: "gayathri-seetharaman-964986158",
  },
  {
    fname: "Shubhangi",
    lname: "Soni",
    role: "CORPORATE DIRECTOR",
    image: "shubhangi.jpeg",
    github: "ShubhangiSoni1603",
    linkedin: "shubhangi-soni",
  },
  {
    fname: "Soumya",
    lname: "Kundu",
    role: "EDITORIAL DIRECTOR",
    image: "soumya.jpeg",
    github: "aymuos15",
    linkedin: "soumya-snigdha-kundu-84b812183",
  },
  {
    fname: "Stuti",
    lname: "Sehgal",
    role: "TECHNICAL DIRECTOR",
    image: "stuti.jpg",
    github: "stutisehgal",
    linkedin: "stuti-sehgal-7a10301b1",
  },
  {
    fname: "Ishika",
    lname: "Gupta",
    role: "PUBLIC RELATIONS DIRECTOR",
    image: "ishika.jpg",
    mail: "ishikag2050@gmail.com",
    linkedin: "findishika",
  }
];

export const advisor = [
  
  {
    fname: "Anush",
    lname: "Bhatia",
    role: "TECHNICAL ADVISOR",
    image: "anush.jpg",
    github: "anushbhatia",
    linkedin: "anush-bhatia-aa500a158",
  },
  {
    fname: "Avirup",
    lname: "Chattaraj",
    role: "TECHNICAL ADVISOR",
    image: "avirup.jpg",
    github: "severussnape123",
    linkedin: "avirupchattaraj",
  },
];

export const techmembers = [
  {
    fname: "Aarsh",
    lname: "Chaube",
    role: "Data Analyst",
    image: "aarsh.jpg",
    github: "Aarsh2001",
    linkedin: "aarsh-chaube-0099521a1",
  },
  {
    fname: "Anant",
    lname: "Kanchan",
    role: "App Developer",
    image: "anant.jpg",
    github: "anantcodes",
    linkedin: "anant-kanchan-0a6b57180",
  },
  {
    fname: "Ananya",
    lname: "Negi",
    role: "Web Developer",
    image: "ananyanegi.jpeg",
    github: "AnanyaNegi",
    linkedin: "ananya-negi-42922018a",
  },
  {
    fname: "Ankit",
    lname: "Hans",
    role: "App Developer",
    image: "ankit.jpeg",
    github: "ankithans",
    linkedin: "ankithans",
  },
  {
    fname: "Ankita",
    lname: "Kokkera",
    role: "ML Developer",
    image: "ankitakokkera.jpg",
    github: "ankitasankars",
    linkedin: "ankita-k-4b943611a",
  },  {
    fname: "Anushka",
    lname: "Garg",
    role: "ML Developer",
    image: "anushkagarg.jpg",
    github: "anushkagarg5653",
    linkedin: "anushka-garg-b6759318a",
  },
  {
    fname: "Arpit",
    lname: "Karnatak",
    role: "Blockchain Developer",
    image: "arpit.jpg",
    github: "",
    linkedin: "arpit-karnatak-255a5a16a",
  },
  {
    fname: "Bhavya",
    lname: "Chhabra",
    role: "ML Developer",
    image: "bhavya.jpg",
    github: "bhavya1600",
    linkedin: "bhavya-chhabra-1600",
  },
  {
    fname: "Devansh",
    lname: "Goswami",
    role: "Web Developer",
    image: "devansh.jpg",
    mail: "devansh51100@gmail.com",
    linkedin: "devansh-goswami-74590a187",
  },
  {
    fname: "Hardik",
    lname: "Srivastava",
    role: "ML Developer",
    image: "hardik.jpg",
    github: "thisishardik",
    linkedin: "hardik-srivastava-2911hs",
  },
  {
    fname: "Ojas",
    lname: "Gupta",
    role: "Flutter & Hadoop Developer",
    image: "ojas.jpg",
    github: "oojas",
    linkedin: "ojasgupta13",
  },
  {
    fname: "Parth",
    lname: "Pandey",
    role: "App Developer",
    image: "parth.png",
    github: "pp2236",
    linkedin: "parth-pandey-b119921a7",
  },
  {
    fname: "Rakesh",
    lname: "J",
    role: "ML Practitioner",
    image: "rakesh j.jpg",
    github: "stagnito",
    linkedin: "rakesh-j-35174618b",
  },
  {
    fname: "Ria",
    lname: "Tyagi",
    role: "Web Developer",
    image: "riatyagi.jpeg",
    github: "riasenpai",
    linkedin: "ria-tyagi-0800381b1",
  },
  {
    fname: "Rohan",
    lname: "Mathur",
    role: "Data Analyst",
    image: "rohan.jpg",
    github: "RohanMathur17",
    linkedin: "rohanmathur17",
  },
  {
    fname: "Rusali",
    lname: "Saha",
    role: "ML Developer",
    image: "rusali.jpg",
    github: "Rusali28",
    linkedin: "rusali-saha-0409921a3",
  },
  {
    fname: "Sampada",
    lname: "Bareja",
    role: "Data Analyst",
    image: "sampada.jpg",
    github: "",
    linkedin: "sampada-bareja-43930818b",
  },
  {
    fname: "Sheel",
    lname: "Patel",
    role: "ML Developer",
    image: "sheel.jpg",
    github: "sheel1206",
    linkedin: "sheel1206",
  },
  {
    fname: "Shinjinee",
    lname: "Maiti",
    role: "ML Developer",
    image: "shinjinee.JPG",
    github: "shinjinee",
    linkedin: "shinjinee-maiti-a1a6ab18b",
  },
  {
    fname: "Tarushi",
    lname: "Pathak",
    role: "ML Developer",
    image: "tarushi.jpg",
    github: "tarushi98",
    linkedin: "tarushi-pathak-6b7b5b177",
  },
  {
    fname: "Tejas",
    lname: "Chintala",
    role: "ML Practitioner",
    image: "tejas.jpg",
    github: "chintalatejas",
    linkedin: "tejas-chintala-752918188",
  },
];

export const designmembers = [
  {
    fname: "Abhimanyu",
    lname: "Bhadauria",
    role: "UI/UX & Graphic Designer",
    image: "abhimanyu.png",
    github: "Mnayu",
    linkedin: "abhimanyu2911",
  },
  {
    fname: "Shubhank",
    lname: "Sargam",
    role: "Video Editing & Sponsorship",
    image: "shubhank.jpeg",
    github: "Shubhankoder",
    linkedin: "shubhanks",
  },
];

export const mgmtmembers = [
  {
    fname: "Devanshi",
    lname: "Karthik",
    role: "Content Writer",
    image: "devanshi.jpeg",
    mail: "devanshi.karthikk@gmail.com",
    linkedin: "devanshi-karthik",
  },
  {
    fname: "Nikunj",
    lname: "Drolia",
    role: "Management",
    image: "nikunkdrolia.jpeg",
    mail: "nik.drolia@gmail.com",
    linkedin: "nikunj-drolia-503a4514b",
  },
  {
    fname: "Shreya",
    lname: "Saha Roy",
    role: "Editorial",
    image: "shreya.jpeg",
    mail: "shreyasaha.roy30@gmail.com",
    linkedin: "shreya-saha-roy-2225651a5",
  },
];
