export const presidents = [
  {
    fname: "Sheel",
    lname: "Patel",
    role: "PRESIDENT ",
    image: "sheel.jpg",
    github: "sheel1206",
    linkedin: "sheel1206",
  },
  {
    fname: "Shaswat",
    lname: "Srivastava",
    role: "VICE PRESIDENT",
    image: "shaswat.jpeg",
    github: "shaas1704",
    linkedin: "shaswat-srivastava-03a67118b/",
  },
];

export const board = [
  {
    fname: "Rakesh",
    lname: "J",
    role: "PROJECTS DIRECTOR",
    image: "rakesh j.jpg",
    github: "stagnito",
    linkedin: "rakesh-j-35174618b",
  },
  {
    fname: "Aarsh",
    lname: "Chaube",
    role: "RESEARCH & DEVELOPMENT DIRECTOR",
    image: "aarsh.jpg",
    github: "Aarsh2001",
    linkedin: "aarsh-chaube-0099521a1",
  },
  {
    fname: "Udit",
    lname: "Dhawan",
    role: "CORPORATE DIRECTOR",
    image: "udit.jpg",
    github: "udit2812",
    linkedin: "udit-dhawan-819762166/",
  },
  {
    fname: "Abhimanyu",
    lname: "Bhadauria",
    role: "CREATIVES DIRECTOR",
    image: "abhimanyu.png",
    github: "Mnayu",
    linkedin: "abhimanyu2911",
  },
  {
    fname: "Shubhank",
    lname: "Sargam",
    role: "CREATIVES DIRECTOR",
    image: "shubhank.jpg",
    github: "shubhanksargam",
    linkedin: "shubhanks/",
  },
  {
    fname: "Ankit",
    lname: "Hans",
    role: "TECHNICAL DIRECTOR",
    image: "ankit.jpeg",
    github: "ankithans",
    linkedin: "ankithans",
  },
  {
    fname: "Palak",
    lname: "Aggarwal",
    role: "ASSOCIATE TECHNICAL DIRECTOR",
    image: "palak.jpeg",
    github: "Palak-Aggarwal1234",
    linkedin: "palak-aggarwal-96366a18b/",
  },
];

export const advisor = [
  
  {
    fname: "Anush",
    lname: "Bhatia",
    role: "TECHNICAL ADVISOR",
    image: "anush.jpg",
    github: "anushbhatia",
    linkedin: "anush-bhatia-aa500a158",
  },
  {
    fname: "Avirup",
    lname: "Chattaraj",
    role: "TECHNICAL ADVISOR",
    image: "avirup.jpg",
    github: "severussnape123",
    linkedin: "avirupchattaraj",
  },
  {
    fname: "Hritik",
    lname: "Bhandari",
    role: "TECHNICAL ADVISOR",
    image: "hritik.jpg",
    github: "hritikbhandari",
    linkedin: "hritikbhandari",
  },
  {
    fname: "Pratyaksh",
    lname: "Bhalla",
    role: "TECHNICAL ADVISOR",
    image: "pratyaksh.jpg",
    github: "pratyaksh64",
    linkedin: "pratyaksh-bhalla-96871b186",
  },
  {
    fname: "Takshil",
    lname: " Mittal",
    role: "EVENTS ADVISOR",
    image: "takshil.jpg",
    github: "takshilmittal",
    linkedin: "takshil-mittal",
  },
  {
    fname: "Akshat",
    lname: "Anand",
    role: "PROJECTS ADVISOR",
    image: "akshat.jpg",
    github: "cipheraxat",
    linkedin: "akshatanand1999",
  },
  {
    fname: "Gayathri",
    lname: "Seetharaman",
    role: "RESEARCH & DEVELOPMENT ADVISOR",
    image: "gayathri.jpg",
    github: "Gayathri621",
    linkedin: "gayathri-seetharaman-964986158",
  },
  {
    fname: "Shubhangi",
    lname: "Soni",
    role: "CORPORATE ADVISOR",
    image: "shubhangi.jpeg",
    github: "ShubhangiSoni1603",
    linkedin: "shubhangi-soni",
  },
  {
    fname: "Soumya",
    lname: "Kundu",
    role: "EDITORIAL ADVISOR",
    image: "soumya.jpeg",
    github: "aymuos15",
    linkedin: "soumya-snigdha-kundu-84b812183",
  },
  {
    fname: "Stuti",
    lname: "Sehgal",
    role: "TECHNICAL ADVISOR",
    image: "stuti.jpg",
    github: "stutisehgal",
    linkedin: "stuti-sehgal-7a10301b1",
  },
  {
    fname: "Ishika",
    lname: "Gupta",
    role: "PUBLIC RELATIONS ADVISOR",
    image: "ishika.jpg",
    mail: "ishikag2050@gmail.com",
    linkedin: "findishika",
  }
];

export const techmembers = [
  {
    fname: "Abhay",
    lname: "Lal",
    role: "ML Engineer",
    image: "abhay.jpg",
    github: "abhay-lal",
    linkedin: "abhay-l-6850111bb/",
  },
  {
    fname: "Adit",
    lname: "Patel",
    role: "Web Developer",
    image: "adit.jpeg",
    github: "anantcodes",
    linkedin: "anant-kanchan-0a6b57180",
  },
  {
    fname: "Aditya",
    lname: "Jain",
    role: "Blockchain Developer",
    image: "aditya.jpeg",
    github: "adityajain2048",
    linkedin: "aditya-jain-b5040a1b8/",
  },
  {
    fname: "Akshat",
    lname: "Saxena",
    role: "ML Engineer",
    image: "akshat.jpeg",
    github: "Akshat1409",
    linkedin: "akshat-saxena-58b5a31a7/",
  },
  {
    fname: "Aman Singh",
    lname: "Kanwar",
    role: "ML Engineer",
    image: "aman.jpg",
    github: "amandotexe",
    linkedin: "aman-kanwar-5955651b8",
  },
  {
    fname: "Anant",
    lname: "Kanchan",
    role: "App Developer",
    image: "anant.jpeg",
    github: "anantcodes",
    linkedin: "anantkanchan/",
  },
  {
    fname: "Ananya",
    lname: "Negi",
    role: "Web Developer",
    image: "ananyanegi.jpeg",
    github: "AnanyaNegi",
    linkedin: "ananya-negi-42922018a",
  },
  {
    fname: "Ankita",
    lname: "Kokkera",
    role: "ML Developer",
    image: "ankita.jpg",
    github: "ankitasankars",
    linkedin: "ankita-k-4b943611a",
  },  
  {
    fname: "Anushree",
    lname: "Bajaj",
    role: "ML Engineer",
    image: "anushree.jpg",
    github: "condescendo",
    linkedin: "anushree-bajaj-7486b71b9/",
  },
  {
    fname: "Arun",
    lname: "Jangra",
    role: "Web Developer",
    image: "arun.jpeg",
    github: "Arun89-crypto",
    linkedin: "arun-jangra-4a94b41b5/",
  },
  {
    fname: "Aryan",
    lname: "Karoliwal",
    role: "ML Engineer",
    image: "aryan.jpg",
    github: "xxNitroprasad",
    linkedin: "aryankaroliwal",
  },
  {
    fname: "Ayush",
    lname: "Jindal",
    role: "ML Developer",
    image: "ayush.jpeg",
    github: "ayushjindal23",
    linkedin: "ayushjindal23/",
  },
  {
    fname: "Chirag",
    lname: "Mathur",
    role: "ML Engineer",
    image: "chirag.jpg",
    github: "chiragmathur27",
    linkedin: "chirag-mathur-40375a1b7",
  },
  {
    fname: "Dimple",
    lname: "Singhvi",
    role: "ML Engineer",
    image: "dimple.jpg",
    github: "DIMPLESINGHVI",
    linkedin: "dimple-singhvi-3015101b5",
  },
  {
    fname: "Eeshan",
    lname: "Dutta",
    role: "Blockchain Developer",
    image: "eeshan.jpg",
    github: "EeshanDutta007",
    linkedin: "eeshan-dutta-03508a1b5",
  },
  {
    fname: "Harikrishnaa",
    lname: "S",
    role: "ML Developer",
    image: "harikrishna.jpg",
    github: "Harikrishnaa3131",
    linkedin: "hk3112/",
  },
  {
    fname: "Harsh",
    lname: "Choubey",
    role: "ML Developer",
    image: "harsh.jpg",
    github: "iamharsh1312",
    linkedin: "iamharsh1312/",
  },
  {
    fname: "Harshit",
    lname: "Aggarwal",
    role: "ML Researcher",
    image: "harshit.jpg",
    github: "harshitaggarwal01",
    linkedin: "harshit-a-46b4a0b7/",
  },
  {
    fname: "Jahnavi",
    lname: "Darbhamulla",
    role: "Web Developer",
    image: "jahnavi.jpg",
    github: "JahnaviDarbhamulla",
    linkedin: "jahnavi-darbhamulla-0a4280201/",
  },
  {
    fname: "Joshikha",
    lname: "M",
    role: "ML Engineer",
    image: "joshikha.jpg",
    github: "mjoshikha",
    linkedin: "mjoshikha1111/",
  },
  {
    fname: "Kotilingesh",
    lname: "",
    role: "Python Developer",
    image: "kotilingesh.jpg",
    github: "Kotilingesh",
    linkedin: "kotilingesh-r-819443216",
  },
  {
    fname: "Kruthi",
    lname: "M",
    role: "ML Engineer",
    image: "kruthi.jpeg",
    github: "Kruthim1304",
    linkedin: "kruthi-m-49b300200/",
  },
  {
    fname: "Lawrence",
    lname: "Swaminathan",
    role: "ML Engineer",
    image: "lawrence.jpeg",
    github: "lawrence1seven",
    linkedin: "lawrence-swaminathan/",
  },
  {
    fname: "Mohnaa",
    lname: "Ghosh",
    role: "Web Developer",
    image: "mohnaa.jpeg",
    github: "Mohnaa",
    linkedin: "mohnaa-ghosh-93567b1b5/",
  },
  {
    fname: "Mubariz",
    lname: "Mohammed",
    role: "Web Developer",
    image: "mubarizuddin.jpeg",
    github: "mubarizzz",
    linkedin: "mubaarizzz/",
  },
  {
    fname: "Naman",
    lname: "Garg",
    role: "ML Engineer",
    image: "naman.jpeg",
    github: "Namangarg110",
    linkedin: "namangarg110/",
  },
  {
    fname: "Naman",
    lname: "Sharma",
    role: "Web Developer",
    image: "Naman.png",
    github: "namanks2201",
    linkedin: "namanks",
  },
  {
    fname: "Parth",
    lname: "Pandey",
    role: "App Developer",
    image: "parth.png",
    github: "pp2236",
    linkedin: "parth-pandey-b119921a7",
  },
  {
    fname: "Pooja",
    lname: "Ravi",
    role: "ML Developer",
    image: "pooja.jpg",
    github: "01pooja10",
    linkedin: "pooja-ravi-9b88861b2",
  },
  {
    fname: "Praveen",
    lname: "Tiwari",
    role: "Blockchain Developer",
    image: "praveen.jpg",
    github: "praveenprakashtiwari",
    linkedin: "praveenprakashtiwari/",
  },  
  {
    fname: "Ria",
    lname: "Tyagi",
    role: "Web Developer",
    image: "riatyagi.jpeg",
    github: "riasenpai",
    linkedin: "ria-tyagi-0800381b1",
  },
  {
    fname: "Rusali",
    lname: "Saha",
    role: "ML Engineer",
    image: "rusali.jpg",
    github: "Rusali28",
    linkedin: "rusali-saha-0409921a3",
  },
  {
    fname: "Shinjinee",
    lname: "Maiti",
    role: "ML Developer",
    image: "shinjinee.JPG",
    github: "shinjinee",
    linkedin: "shinjinee-maiti-a1a6ab18b",
  },
  {
    fname: "Shubham",
    lname: "Gore",
    role: "ML Developer",
    image: "Shubham.jpeg",
    github: "shubhamgore2468",
    linkedin: "shubham-gore-b36612118/",
  },
  {
    fname: "Suvodeep",
    lname: "Sinha",
    role: "Research and Development",
    image: "suvodeep.jpg",
    github: "Suvoo",
    linkedin: "suvodeep-sinha-59652418b",
  },
  {
    fname: "Tanmay",
    lname: "Agrawal",
    role: "ML Engineer",
    image: "tanmay.jpg",
    github: "Vector3103",
    linkedin: "tanmay-agrawal-b685531b0",
  },
  {
    fname: "Thrishalini",
    lname: "Dwaraknath",
    role: "ML Engineer",
    image: "thrishalini.jpg",
    github: "thrishalini1",
    linkedin: "thrishalini-d-3234b21b7/",
  },
  {
    fname: "Utkarsh",
    lname: "Upendra",
    role: "ML Engineer",
    image: "utkarsh.JPG",
    github: "Utkarsh3012",
    linkedin: "utkarsh-upendra-b382891ba/",
  },
  {
    fname: "V S",
    lname: "Gopalakrishnan",
    role: "Web Developer",
    image: "gopalkrishanan.jpeg",
    github: "goviv",
    linkedin: "gopalakrishnan-v-s-vivek-a247621bb/",
  },
  {
    fname: "Ved Prakash",
    lname: "Dubey",
    role: "ML Developer",
    image: "ved.jpeg",
    github: "VedPDubey",
    linkedin: "ved-prakash-dubey-swash/",
  },
  {
    fname: "Yogesh",
    lname: "A",
    role: "ML Engineer",
    image: "yogesh.jpg",
    github: "Narsil2",
    linkedin: "yogesh-a-6248691b7",
  },
  {
    fname: "Yohenba",
    lname: "Kshetrimayum",
    role: "Blockchain Developer",
    image: "yohenba.png",
    github: "Yohenba18",
    linkedin: "yohenba-kshetrimayum-74164a190/",
  },
];

export const designmembers = [
  {
    fname: "Anchal",
    lname: "Porwal",
    role: "Graphic Designer",
    image: "anchal.jpg",
    github: "Anchal1226",
    linkedin: "anchal-porwal",
  },
  {
    fname: "Elina",
    lname: "Singh",
    role: "Video Editor",
    image: "elina.jpeg",
    github: "elina7344",
    linkedin: "elina-singh-4841111b8",
  },
  {
    fname: "Natansh",
    lname: "Rajesh",
    role: "Video Editor",
    image: "natansh.JPG",
    github: "mathurnatansh",
    linkedin: "",
  },
  {
    fname: "Sharon",
    lname: "Sujitha A",
    role: "Graphic & UI Desginer",
    image: "sharon.jpg",
    mail: "sharonsuji7@gmail.com",
    linkedin: "",
  },
  {
    fname: "Syed",
    lname: "Amaan Ariz",
    role: "Designer",
    image: "syed.jpg",
    github: "SYEDAMAAN05",
    linkedin: "syed-amaan-430a7b1b2",
  },
  {
    fname: "Tanisha",
    lname: "Kapoor",
    role: "Graphic Designer",
    image: "tanisha.jpg",
    github: "tanishakapoor11",
    linkedin: "tanisha-kapoor-4713261a0/",
  },
];

export const mgmtmembers = [
  {
    fname: "Abhishek",
    lname: "Dubey",
    role: "Content Writer",
    image: "abhishekDubey.jpg",
    github: "",
    linkedin: "abhishek-dubey-4b76161b8",
  },
  {
    fname: "Aishani",
    lname: "Singh",
    role: "Corporate Associate",
    image: "aishani.jpg",
    github: "aishanii",
    linkedin: "aishani-singh-a651191a6",
  },
  {
    fname: "Anant Dev",
    lname: "Kapoor",
    role: "Public Relations",
    image: "anantdev.jpg",
    github: "anantdevkapoor",
    linkedin: "anant-dev-kapoor-b29101b3/",
  },
  {
    fname: "Arpita",
    lname: "Singh",
    role: "Content Writer",
    image: "arpita.jpeg",
    github: "arpitasingh13",
    linkedin: "arpitasingh1301/",
  },
  {
    fname: "Diya",
    lname: "Sabu",
    role: "Content Writer",
    image: "diya.jpg",
    github: "diyasabu",
    linkedin: "diya-sabu-b3750b18b",
  },
  {
    fname: "Nikhil",
    lname: "Chandnani",
    role: "Events",
    image: "nikhil.jpeg",
    mail: "",
    linkedin: "nikhil-chandnani-2002",
  },
  {
    fname: "Ritu Raj",
    lname: "Singh",
    role: "Corporate Associate",
    image: "ritu.jpg",
    github: "rrsingh11",
    linkedin: "ritu-raj-singh-5a644b1b8/",
  },
  {
    fname: "Sai",
    lname: "Sreeprada T",
    role: "Management ",
    image: "sreeprada.jpg",
    github: "Sreeprada6303",
    linkedin: "sai-sreeprada-t-4685211bb",
  },
  {
    fname: "Shambhavi",
    lname: "Jha",
    role: "Corporate Associate",
    image: "shambhavi.png",
    mail: "",
    linkedin: "shambhavijha15/",
  },
  {
    fname: "SRUTI",
    lname: "MANDAL",
    role: "Event Manager",
    image: "sruti.jpg",
    github: "srutimandal12",
    linkedin: "srutimandal12/",
  },
];
